openapi: 3.0.3
info:
  title: 참여형 프로모션 임시 document
  description: |-
    https://api04.escm.dev.kurly.com/api-contract/
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://api04.escm.dev.kurly.com/api-contract/
paths:
  /shared/test/{promotionId}:
    get:
      summary: test
      description: test
      parameters:
        - name: promotionId
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                "유효한 요청": 
                  value: {"data": {"test":1}}
        '400':
          description: failed
          content:
            application/json:
              examples:
                "찾을수 없는 요청": 
                  value: {"errorCode": "NOT_FOUND"}
      security:
        - bearerAuthJWT: []
components:
  securitySchemes:
    bearerAuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
